spring.application.name=social_account_business
spring.datasource.url=jdbc:postgresql://pg-a7b66d0-khanhlee101102-2c47.h.aivencloud.com:15217/defaultdb?ssl=require&user=avnadmin&password=AVNS_4XENajFmsgkgMY6R2zh
spring.datasource.hikari.ssl=true
spring.datasource.hikari.ssl-mode=REQUIRE
# If Aiven provides a CA cert (recommended for production):
spring.datasource.hikari.ssl-root-cert=classpath:/cer/db2.pem
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_4XENajFmsgkgMY6R2zh
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.default-schema=public
#spring.datasource.hikari.ssl-root-cert=./src/main/resources/cer/root.crt
#url=jdbc:${JDBC_URL}
#username=${DB_USERNAME}
#password=${DB_PASSWORD}

spring.liquibase.change-log=classpath:/liquibase/db.changelog-master.xml
spring.liquibase.enabled=true

# SERVER
server.port = 7070
#server.servlet.context-path=/api
spring.main.allow-bean-definition-overriding=true

#thread pool
thread.pool.core.size=10
thread.pool.max.size=50
thread.pool.queue.capacity=100


# Date Jackson formation
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=UTC

#JWT security
jwt.secret-key=eHNhbmduZ3V5ZW44OHNvY2lhbGFjY291bnRidXNpbmVzc3dlYmFwcA==
jwt.access-token.expiration=604800000
jwt.refresh-token.expiration=1800000
jwt.cookie.access-token.name=c_user
jwt.cookie.refresh-token.name=rft
jwt.cookie.domain=localhost
jwt.cookie.secure=false
jwt.sepay.secret-key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTZXJ2aWNlc0Bza21lZGlhMjRoLmNvbSIsImlzcyI6InNhYi1hdXRoZW50aWNhdGlvbi1zeXN0ZW0iLCJhdWQiOiJzZXBheS13ZWJob29rIiwidHlwZSI6IkFQSV9LRVkiLCJpYXQiOjE3NDQzNjYyNjh9.3EUpjabTvYH7HkxoXUXwAQLi-jLJkQzPQlBeNKu2w6w

# Servlet Multipart
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
spring.servlet.multipart.enabled=true
server.error.whitelabel.enabled=false

# JSON handling
spring.jackson.deserialization.fail-on-unknown-properties=false
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=services@skmedia24h.com
spring.mail.password=lxin ysua lfob edia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha

# Actuator Configuration
springdoc.show-actuator=true
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/manage
management.endpoint.health.show-details=always
management.endpoints.web.cors.allowed-origins=http://localhost:7070
management.endpoints.web.cors.allowed-methods=GET,POST

#logging
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null
server.error.include-message=always
server.error.include-binding-errors=always


# Sepay bank account
sepay.bank.accountNo=7101700733
sepay.bank.bankName=BIDV

# currency converter
currency-converter.api-key=fca_live_pIS0nhzvSeIHBV1tWwbxde9pzt9l0vvzoX0dlIyg
