changeLogFile= src/main/resources/db.changelog-master.xml
#changeLogFile= src/main/resources/db.changelog-check-master.xml
logging= debug
driver= org.postgresql.Driver
url= jdbc:postgresql://pg-2850c47d-leekhan101102-68d0.c.aivencloud.com:23276/defaultdb?ssl=require
#url=jdbc:postgresql://pg-f0c490e-gaukoalabienhinh123-36f4.l.aivencloud.com:27851/defaultdb?ssl=require

username=avnadmin
#password=AVNS_pmrqzj1BwuvIMFFPt7i
password=AVNS_nfRlSgvyNGrUexic8PD

# generate "virtual db" out of hibernate entities
referenceUrl=hibernate:spring:org.project.social_account_business.model?dialect=org.hibernate.dialect.PostgreSQLDialect&amp;hibernate.implicit.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver